env:
  global:
    # DOCKERHUB_TRIGGER_TOKEN to trigger a build on dockerhub
    secure: "Nh1P7qQB0oj7nRthRHL5jQBsP8hxeHgikv+Qn9xpDqY3Ay1IWQA02WtXtfpf8n8xxIig6hKCR2QXyiKmx0+GKFTtbxCIuvg4Sxwvq6kYr0tsUzwc/K3RWJH6zfPao6CFryp6GXVO1M8JjHm0e0hn1aMi0gZ5Wge9eH3EVuNPdqOgnEN4hIJ0NGY6xYG7gckEUZMqRC0HWyAVVtQ4sF7/M9skp7DXwzWLwC4O9g5dL4LgSWN0xwHlvENS77dQ4Uus9LiECVGvKz5EX+9+eM/ZrKF/iwcLv3mJJk6Oxbzl14amcW3mPdaby/Hepoy+6K6YyfVw1KD9VoHaqcd5Se3JpEit/qyYm9glPKOosSVG6tqxtstoidSp6hXLscb6eyCdcXKND8/kUKcoLvHrK3Bqt0FTO/AOGL+mKtklFmRXgoqZgn+1tzVgQFnx50YUXXtJKxZICrUPB2XwWnsVHDEVb3Q1+jcrZUQE6D0x3l3n2lT292FjwhnL91EC1h+BsA6H0HwD9/3DXPcb2/EJJ53uWYZZ0hRuSxkVnFPzuIvx26p/pDP4gcJHu4VsjpnKmFx70oY+6z9xMdBBlpZIX/UdzGY7ZPzu/LvKEW72ccAt6kJqMzo5qMwZh9SM0JPT+4Eft/R3YFExYE124n0NOpPL3sYa2uAKgh3gce1joo6kZRc="

branches:
  only:
    - master

language: node_js
node_js:
  - '4'

sudo: required
services:
  - docker

install:
  - npm install
  - make build

script:
  - make lint
  - make test

after_success:
  - curl -XPOST https://registry.hub.docker.com/u/fluxs/phantomjs-worker/trigger/"$DOCKERHUB_TRIGGER_TOKEN"/
